image: alpine/git:latest
pipelines:
  branches:
    '*':
      - step:
          name: Sync GitHub Mirror
          clone:
            enabled: false
          script:
            - git clone --bare https://bitbucket.org/ckolivas/ckpool.git ckpool.git
            - cd ckpool.git
            - git remote set-url --push origin "https://x-token-auth:${GITHUB_TOKEN}@github.com/ckolivas/ckpool.git"
            - git push --mirror origin
