[package]
name = "bitcoind-harness"
description = "Harness for interacting with bitcoind"
version = "0.0.1"

authors.workspace = true
edition.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
bitcoin.workspace = true
tempfile = "3.20.0"
