#!/usr/bin/env bash

set -euxo pipefail

cp deploy/bitcoind.service /etc/systemd/system/

mkdir -p /etc/bitcoin
cp deploy/bitcoin.conf /etc/bitcoin/bitcoin.conf

if [[ ! -e ~/.bitcoin/bitcoin.conf ]]; then
  mkdir -p ~/.bitcoin
  ln -s /etc/bitcoin/bitcoin.conf ~/.bitcoin/bitcoin.conf
fi

journalctl --unit bitcoind --vacuum-time 5m

systemctl daemon-reload
systemctl enable bitcoind
systemctl restart bitcoind
