#!/usr/bin/env bash

set -euxo pipefail

cd ckpool
./autogen.sh
./configure
make
install --backup src/ckpool /usr/local/bin/ckpool
cd ..

journalctl --unit ckpool --vacuum-time 5m

cp deploy/ckpool.service /etc/systemd/system/

mkdir -p /etc/ckpool
cp deploy/ckpool.conf /etc/ckpool/ckpool.conf

systemctl daemon-reload
systemctl enable ckpool
systemctl restart ckpool
