#!/usr/bin/env bash

set -euxo pipefail

if [[ ! -e ~/.cargo/env ]]; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
fi

source ~/.cargo/env

rustup update stable

cd para
cargo build --release
install --backup target/release/para /usr/local/bin/para
cd ..

journalctl --unit para --vacuum-time 1s

cp deploy/para.service /etc/systemd/system/

systemctl daemon-reload
systemctl enable para
systemctl restart para
