#!/usr/bin/env bash

# This script is idempotent.

set -euxo pipefail

CHAIN=$1
DOMAIN=$2

export DEBIAN_FRONTEND=noninteractive

touch ~/.hushlogin

hostnamectl set-hostname $DOMAIN

apt-get install --yes \
  acl \
  autoconf \
  automake \
  build-essential \
  clang \
  cmake \
  curl \
  libboost-dev \
  libevent-dev \
  libpq-dev \
  libsqlite3-dev\
  libssl-dev \
  libtool \
  libzmq3-dev \
  locales-all \
  nginx \
  pkg-config \
  pkgconf \
  postgresql \
  postgresql-contrib \
  python3 \
  ufw \
  vim \
  yasm

apt-get remove --yes --auto-remove

ufw default allow outgoing
ufw default deny incoming

ufw allow http
ufw allow 3333
ufw allow ssh

case $CHAIN in
  main)
    ufw allow 8333
    ;;
  regtest)
    ufw allow 18444
    ;;
  signet)
    # Local signet only
    # ufw allow 38333
    ;;
  test)
    ufw allow 18333
    ;;
  testnet4)
    ufw allow 48333
    ;;
  *)
    echo "Unknown chain: $CHAIN"
    exit 1
    ;;
esac

mkdir -p \
  /etc/systemd/system/bitcoind.service.d \
  /etc/systemd/system/ckpool.service.d

OVERRIDE=/etc/systemd/system/ckpool.service.d/override.conf

echo '[Service]' > $OVERRIDE
echo "Environment=CHAIN=$CHAIN" >> $OVERRIDE

cp $OVERRIDE /etc/systemd/system/bitcoind.service.d/override.conf

sed -i -E 's/#?PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
sshd -t
systemctl restart sshd

ufw --force enable

if ! which bitcoind; then
  ./bin/install-bitcoin-core-linux
fi

bitcoind --version

rm -f /var/lib/bitcoind/settings.json

cd ckpool
./autogen.sh
./configure
make
install --backup src/ckpool /usr/local/bin/ckpool
cd ..

id --user bitcoin || useradd --system bitcoin
id --user ckpool || useradd --system ckpool

cp deploy/bitcoind.service /etc/systemd/system/

mkdir -p /etc/bitcoin
cp deploy/bitcoin.conf /etc/bitcoin/bitcoin.conf

if [[ ! -e ~/.bitcoin/bitcoin.conf ]]; then
  mkdir -p ~/.bitcoin
  ln -s /etc/bitcoin/bitcoin.conf ~/.bitcoin/bitcoin.conf
fi

mkdir -p /etc/nginx/sites-available
mkdir -p /etc/nginx/sites-enabled

cp deploy/nginx.conf /etc/nginx/sites-available/nginx.conf

ln -sf /etc/nginx/sites-available/nginx.conf /etc/nginx/sites-enabled/nginx.conf

mkdir -p /var/lib/ckpool/logs
chown -R ckpool:ckpool /var/lib/ckpool
chmod -R 755 /var/lib/ckpool/logs

nginx -t
systemctl enable nginx
systemctl restart nginx

journalctl --unit bitcoind --vacuum-time 5m

systemctl daemon-reload
systemctl enable bitcoind
systemctl restart bitcoind

./bin/postgres-init

if [ "$CHAIN" == "signet" ]; then
  git submodule update --init
  cd bitcoin
  cmake -B build
  cmake --build build -j 21
  cd ..
  ./bin/mine
fi

journalctl --unit ckpool --vacuum-time 5m

cp deploy/ckpool.service /etc/systemd/system/

mkdir -p /etc/ckpool
cp deploy/ckpool.conf /etc/ckpool/ckpool.conf

systemctl daemon-reload
systemctl enable ckpool
systemctl restart ckpool

# TODO: add a curl or something that checks that ckpool is running
