use {
    super::*,
    axum::extract::{Path, State},
    http_server::{
        self,
        error::{OptionExt, ServerResult},
        templates::{DashboardHtml, PoolHtml, ProxyHtml, UserHtml, UsersHtml},
    },
};

pub mod pool;
pub mod proxy;
pub mod router;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PoolStatus {
    pub endpoint: String,
    pub users: usize,
    pub workers: usize,
    pub sessions: usize,
    pub disconnected: usize,
    pub idle: usize,
    pub hashrate_1m: HashRate,
    pub hashrate_5m: HashRate,
    pub hashrate_15m: HashRate,
    pub hashrate_1hr: HashRate,
    pub hashrate_6hr: HashRate,
    pub hashrate_1d: HashRate,
    pub hashrate_7d: HashRate,
    pub sps_1m: f64,
    pub sps_5m: f64,
    pub sps_15m: f64,
    pub sps_1hr: f64,
    pub accepted_shares: u64,
    pub rejected_shares: u64,
    pub blocks: u64,
    pub best_ever: Option<Difficulty>,
    pub last_share: Option<u64>,
    pub accepted_work: TotalWork,
    pub rejected_work: TotalWork,
    pub ph_days: PhDays,
    pub uptime_secs: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProxyStatus {
    pub endpoint: String,
    pub users: usize,
    pub workers: usize,
    pub sessions: usize,
    pub disconnected: usize,
    pub idle: usize,
    pub hashrate_1m: HashRate,
    pub hashrate_5m: HashRate,
    pub hashrate_15m: HashRate,
    pub hashrate_1hr: HashRate,
    pub hashrate_6hr: HashRate,
    pub hashrate_1d: HashRate,
    pub hashrate_7d: HashRate,
    pub sps_1m: f64,
    pub sps_5m: f64,
    pub sps_15m: f64,
    pub sps_1hr: f64,
    pub accepted_shares: u64,
    pub rejected_shares: u64,
    pub best_ever: Option<Difficulty>,
    pub last_share: Option<u64>,
    pub accepted_work: TotalWork,
    pub rejected_work: TotalWork,
    pub ph_days: PhDays,
    pub uptime_secs: u64,
    pub upstream_endpoint: String,
    pub upstream_connected: bool,
    pub upstream_ping: u128,
    pub upstream_difficulty: Difficulty,
    pub upstream_username: Username,
    pub upstream_enonce1: Extranonce,
    pub upstream_enonce2_size: usize,
    pub upstream_version_mask: Option<Version>,
    pub upstream_accepted: u64,
    pub upstream_rejected: u64,
    pub upstream_filtered: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserDetail {
    pub address: String,
    pub hashrate_1m: HashRate,
    pub hashrate_5m: HashRate,
    pub hashrate_15m: HashRate,
    pub hashrate_1hr: HashRate,
    pub hashrate_6hr: HashRate,
    pub hashrate_1d: HashRate,
    pub hashrate_7d: HashRate,
    pub sps_1m: f64,
    pub sps_5m: f64,
    pub sps_15m: f64,
    pub sps_1hr: f64,
    pub accepted_shares: u64,
    pub rejected_shares: u64,
    pub best_ever: Option<Difficulty>,
    pub last_share: Option<u64>,
    pub accepted_work: TotalWork,
    pub rejected_work: TotalWork,
    pub ph_days: PhDays,
    pub sessions: usize,
    pub authorized: u64,
    pub workers: Vec<WorkerDetail>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkerDetail {
    pub name: String,
    pub sessions: usize,
    pub hashrate_1m: HashRate,
    pub hashrate_5m: HashRate,
    pub hashrate_15m: HashRate,
    pub hashrate_1hr: HashRate,
    pub hashrate_6hr: HashRate,
    pub hashrate_1d: HashRate,
    pub hashrate_7d: HashRate,
    pub sps_1m: f64,
    pub sps_5m: f64,
    pub sps_15m: f64,
    pub sps_1hr: f64,
    pub accepted_shares: u64,
    pub rejected_shares: u64,
    pub best_ever: Option<Difficulty>,
    pub last_share: Option<u64>,
    pub accepted_work: TotalWork,
    pub rejected_work: TotalWork,
    pub ph_days: PhDays,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RouterStatus {
    pub upstream_count: usize,
    pub session_count: usize,
    pub hashrate_1m: HashRate,
    pub ph_days: PhDays,
    pub slots: Vec<SlotStatus>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SlotStatus {
    pub upstream_id: u32,
    pub endpoint: String,
    pub username: String,
    pub hashrate_1m: HashRate,
    pub session_count: usize,
    pub ph_days: PhDays,
    pub hashrate_min: HashRate,
    pub hashrate_max: HashRate,
    pub hashrate_avg: HashRate,
    pub hashrate_median: HashRate,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpstreamDetail {
    pub upstream_id: u32,
    pub endpoint: String,
    pub username: String,
    pub connected: bool,
    pub ping_ms: u128,
    pub difficulty: Difficulty,
    pub enonce1: Extranonce,
    pub enonce2_size: usize,
    pub version_mask: Option<Version>,
    pub accepted: u64,
    pub rejected: u64,
    pub filtered: u64,
    pub users: usize,
    pub workers: usize,
    pub session_count: usize,
    pub disconnected: usize,
    pub idle: usize,
    pub hashrate_1m: HashRate,
    pub hashrate_5m: HashRate,
    pub hashrate_15m: HashRate,
    pub hashrate_1hr: HashRate,
    pub hashrate_6hr: HashRate,
    pub hashrate_1d: HashRate,
    pub hashrate_7d: HashRate,
    pub sps_1m: f64,
    pub sps_5m: f64,
    pub sps_15m: f64,
    pub sps_1hr: f64,
    pub accepted_shares: u64,
    pub rejected_shares: u64,
    pub best_ever: Option<Difficulty>,
    pub last_share: Option<u64>,
    pub accepted_work: TotalWork,
    pub rejected_work: TotalWork,
    pub ph_days: PhDays,
    pub uptime_secs: u64,
    pub sessions: Vec<SessionDetail>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionDetail {
    pub id: SessionId,
    pub upstream_id: u32,
    pub address: String,
    pub workername: String,
    pub username: String,
    pub enonce1: Extranonce,
    pub version_mask: Option<Version>,
    pub accepted_shares: u64,
    pub rejected_shares: u64,
    pub accepted_work: TotalWork,
    pub rejected_work: TotalWork,
    pub best_ever: Option<Difficulty>,
    pub last_share: Option<u64>,
    pub ph_days: PhDays,
    pub hashrate_1m: HashRate,
    pub hashrate_5m: HashRate,
    pub hashrate_15m: HashRate,
    pub hashrate_1hr: HashRate,
    pub hashrate_6hr: HashRate,
    pub hashrate_1d: HashRate,
    pub hashrate_7d: HashRate,
    pub sps_1m: f64,
    pub sps_5m: f64,
    pub sps_15m: f64,
    pub sps_1hr: f64,
}

pub type BitcoinStatus = http_server::BitcoinStatus;
pub type SystemStatus = http_server::SystemStatus;
